// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smeedee.iOS {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("WorkingDaysLeftWidget")]
	public partial class WorkingDaysLeftWidget {
		
		private MonoTouch.UIKit.UILabel __mt_daysLabel;
		
		private MonoTouch.UIKit.UILabel __mt_topLabel;
		
		private MonoTouch.UIKit.UILabel __mt_bottomLabel;
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("daysLabel")]
		private MonoTouch.UIKit.UILabel daysLabel {
			get {
				this.__mt_daysLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("daysLabel")));
				return this.__mt_daysLabel;
			}
			set {
				this.__mt_daysLabel = value;
				this.SetNativeField("daysLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("topLabel")]
		private MonoTouch.UIKit.UILabel topLabel {
			get {
				this.__mt_topLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("topLabel")));
				return this.__mt_topLabel;
			}
			set {
				this.__mt_topLabel = value;
				this.SetNativeField("topLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("bottomLabel")]
		private MonoTouch.UIKit.UILabel bottomLabel {
			get {
				this.__mt_bottomLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("bottomLabel")));
				return this.__mt_bottomLabel;
			}
			set {
				this.__mt_bottomLabel = value;
				this.SetNativeField("bottomLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
	}
}
