// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smeedee.iOS {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("BuildStatusTableCellController")]
	public partial class BuildStatusTableCellController {
		
		private MonoTouch.UIKit.UITableViewCell __mt_cell;
		
		private MonoTouch.UIKit.UILabel __mt_buildStatusLabel;
		
		private MonoTouch.UIKit.UILabel __mt_lastBuildTimeLabel;
		
		private MonoTouch.UIKit.UILabel __mt_projectNameLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("cell")]
		private MonoTouch.UIKit.UITableViewCell cell {
			get {
				this.__mt_cell = ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("cell")));
				return this.__mt_cell;
			}
			set {
				this.__mt_cell = value;
				this.SetNativeField("cell", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buildStatusLabel")]
		private MonoTouch.UIKit.UILabel buildStatusLabel {
			get {
				this.__mt_buildStatusLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("buildStatusLabel")));
				return this.__mt_buildStatusLabel;
			}
			set {
				this.__mt_buildStatusLabel = value;
				this.SetNativeField("buildStatusLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lastBuildTimeLabel")]
		private MonoTouch.UIKit.UILabel lastBuildTimeLabel {
			get {
				this.__mt_lastBuildTimeLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("lastBuildTimeLabel")));
				return this.__mt_lastBuildTimeLabel;
			}
			set {
				this.__mt_lastBuildTimeLabel = value;
				this.SetNativeField("lastBuildTimeLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("projectNameLabel")]
		private MonoTouch.UIKit.UILabel projectNameLabel {
			get {
				this.__mt_projectNameLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("projectNameLabel")));
				return this.__mt_projectNameLabel;
			}
			set {
				this.__mt_projectNameLabel = value;
				this.SetNativeField("projectNameLabel", value);
			}
		}
	}
}
