// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smeedee.iOS {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("CommitTableCellController")]
	public partial class CommitTableCellController {
		
		private MonoTouch.UIKit.UILabel __mt_username;
		
		private MonoTouch.UIKit.UILabel __mt_timestamp;
		
		private MonoTouch.UIKit.UIImageView __mt_image;
		
		private MonoTouch.UIKit.UITableViewCell __mt_cell;
		
		private MonoTouch.UIKit.UILabel __mt_message;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("username")]
		private MonoTouch.UIKit.UILabel username {
			get {
				this.__mt_username = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("username")));
				return this.__mt_username;
			}
			set {
				this.__mt_username = value;
				this.SetNativeField("username", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("timestamp")]
		private MonoTouch.UIKit.UILabel timestamp {
			get {
				this.__mt_timestamp = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("timestamp")));
				return this.__mt_timestamp;
			}
			set {
				this.__mt_timestamp = value;
				this.SetNativeField("timestamp", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("image")]
		private MonoTouch.UIKit.UIImageView image {
			get {
				this.__mt_image = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("image")));
				return this.__mt_image;
			}
			set {
				this.__mt_image = value;
				this.SetNativeField("image", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("cell")]
		private MonoTouch.UIKit.UITableViewCell cell {
			get {
				this.__mt_cell = ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("cell")));
				return this.__mt_cell;
			}
			set {
				this.__mt_cell = value;
				this.SetNativeField("cell", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("message")]
		private MonoTouch.UIKit.UILabel message {
			get {
				this.__mt_message = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("message")));
				return this.__mt_message;
			}
			set {
				this.__mt_message = value;
				this.SetNativeField("message", value);
			}
		}
	}
}
