//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int BtnGlobalSettings = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int BtnNext = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int BtnPrev = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int BtnWidgetSettings = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int Flipper = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int RootLayout = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int TopBanner = 2131099649;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int Main = 2131034112;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int FooWidgetText = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int GlobalSettings = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Next = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Prev = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int TestWidgetText = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int WidgetSettings = 2130968583;
			
			private String()
			{
			}
		}
	}
}
