//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smeedee.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int AccessKeyInput = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int BtnEnabledWidgets = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int BtnGlobalSettings = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int BtnNext = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int BtnPrev = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int BtnServerSettings = 2131099654;
			
			// aapt resource value: 0x7f060016
			public const int BtnWidgetSettings = 2131099670;
			
			// aapt resource value: 0x7f06000c
			public const int ErrorNotificationText = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int Flipper = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int GlobalSettingsHeadline = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int GlobalSettingsTopBanner = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int LinearLayout01 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ListView01 = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int LoginButton = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int LoginLinearLayout = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int RootLayout = 2131099650;
			
			// aapt resource value: 0x7f060012
			public const int ServerSettingsScreenTextView = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int ServerUrlInput = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int SmeedeeIcon = 2131099657;
			
			// aapt resource value: 0x7f060013
			public const int SmeedeeStartPageTextView = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int TopBanner = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int WorkingDaysLeftNumber = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int WorkingDaysLeftText = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int mainlayout = 2131099655;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EnabledWidgetsScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GlobalSettingsScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ServerSettingsScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StartPageWidget = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int WorkingDaysLeftWidget = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int Main = 2131034112;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int BtnEnabledWidgets = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int BtnServerSettings = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int EnabledWidgets = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int GlobalSettings = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int LoginScreen = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int LoginWidgetTestText = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int Next = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int Prev = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int ServerSettings = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int StartPageWidget = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int WidgetSettings = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int WorkingDaysLeft = 2130968587;
			
			private String()
			{
			}
		}
	}
}
