// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smeedee.iOS {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("LabelTextInputTableCellController")]
	public partial class LabelTextInputTableCellController {
		
		private MonoTouch.UIKit.UITableViewCell __mt_view;
		
		private MonoTouch.UIKit.UITextField __mt_textInput;
		
		private MonoTouch.UIKit.UITableViewCell __mt_cell;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UITableViewCell view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("textInput")]
		private MonoTouch.UIKit.UITextField textInput {
			get {
				this.__mt_textInput = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("textInput")));
				return this.__mt_textInput;
			}
			set {
				this.__mt_textInput = value;
				this.SetNativeField("textInput", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("cell")]
		private MonoTouch.UIKit.UITableViewCell cell {
			get {
				this.__mt_cell = ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("cell")));
				return this.__mt_cell;
			}
			set {
				this.__mt_cell = value;
				this.SetNativeField("cell", value);
			}
		}
	}
}
